#!/bin/bash


# Setup a 1 GB RAM Disk
if [[ "$(uname -s)" = "Darwin" ]]; then

  RAM_DISK="/Volumes/RAM Disk"
  if [ ! -d "$RAM_DISK" ]; then
    diskutil erasevolume HFS+ 'RAM Disk' `hdiutil attach -nomount ram://2048000`
    echo "You can eject with `diskutil unmount 'RAM Disk'`"
  fi

else
  echo "WARNING: Manual setup of RAM_DISK required on *nix systems."
  RAM_DISK=ramdisk

  # RAM_DISK="/mnt/ramdisk"
  # if [ ! -d "$RAM_DISK" ]; then
  #   sudo su
  #   mkdir "$RAM_DISK"
  #   mount -t tmpfs -o size=1G tmpfs "$RAM_DISK"
  #   chown $(whoami): "$RAM_DISK"
  # fi
fi

# Link the tree-sitter afl test harness and copy over inputs.
WD=$(pwd)
cd "$RAM_DISK"

if [[ "$(uname -s)" = "Darwin" ]]; then
  # disable fseventd for this volume on macOS
  mkdir -p .fseventsd && touch .fseventsd/no_log
fi

for lang in go javascript ruby; do
  ln -s $WD/afl-$lang
done
ln -s $WD/dictionaries/
ln -s $WD/script/fuzz
cp -r $WD/afl_in/ afl_in/
