#!/bin/bash

set -e

# Setup a 1 GB RAM Disk
diskutil erasevolume HFS+ 'RAM Disk' `hdiutil attach -nomount ram://2048000`
# You can eject like so:
# diskutil unmount 'RAM Disk'

# Link the tree-sitter afl test harness and copy over inputs.
WD=$(pwd)
cd /Volumes/RAM\ Disk
mkdir -p .fseventsd && touch .fseventsd/no_log # disable fseventd for this volume.
ln -s $WD/afl afl
ln -s $WD/script/fuzz fuzz
cp -r $WD/afl_in/ afl_in/
mkdir -p afl_out
